<?php


namespace app\admin\controller;


use think\Controller;
use think\facade\Session;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//        Session::clear();
        if(!Session::has('uid')){
             $this->redirect('Login/Login/index');
        }
    }
}